name: CI/CD

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rsync to dev server
        uses: burnett01/rsync-deployments@v2
        with:
          switches: -avzr --delete
          remote_path: /home/alt/fast-api
          remote_host: 10.17.10.6
          remote_user: ${{ secrets.DEV_SERVER_USER }}
          remote_pass: ${{ secrets.DEV_SERVER_PASS }}

      - name: Run uvicorn on dev server
        run: |
          ssh ${{ secrets.DEV_SERVER_USER }}@10.17.10.6 "cd /home/alt/fast-api && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  deploy_prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rsync to prod server
        uses: burnett01/rsync-deployments@v2
        with:
          switches: -avzr --delete
          remote_path: /home/alt/fast-api
          remote_host: 10.17.10.17
          remote_user: ${{ secrets.PROD_SERVER_USER }}
          remote_pass: ${{ secrets.PROD_SERVER_PASS }}

      - name: Run uvicorn on prod server
        run: |
          ssh ${{ secrets.PROD_SERVER_USER }}@10.17.10.17 "cd /home/alt/fast-api && uvicorn app.main:app --host 0.0.0.0 --port 8000"
